# Site settings
title: Luca Moiana
email: luca_moiana@hotmail.com  
description: "This is just a test page for my awesome BLOG."
baseurl: ""
url: "http://lucamoiana.github.io"
twitter_username: lucamoiana
github_username:  lucamoiana

# Build settings
markdown: kramdown
permalink: pretty
